# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_packagedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageDetails',
        ),
        migrations.AddField(
            model_name='packages',
            name='stripe_id',
            field=models.CharField(default='', max_length=224),
        ),
    ]
