# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20180117_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='stripe_id',
            new_name='plan_id',
        ),
    ]
