# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(blank=True, default='', max_length=224),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_id',
            field=models.CharField(blank=True, default='', max_length=224),
        ),
    ]
