# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180117_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='plan',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stripe_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
