# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180117_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='stripe_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
