# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
