# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
