# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180113_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='avgrating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overallreview', to='products.Product')),
            ],
        ),
    ]
