# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_avgrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avgrating',
            name='product',
        ),
    ]
