# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_avgrating_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='avgrating',
        ),
    ]
