# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180119_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
